disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - for_where
  - cyclomatic_complexity
  - function_body_length
  - unused_optional_binding
  - type_body_length
  - identifier_name
  - type_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
