name: build  


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
    
jobs:
  build:
  runs-on: macOS-latest

steps:
- name: Checkout
- uses: actions/checkout@v2
- name: Select Xcode
  run: sudo xcode-select -switch /Applications/Xcode_11.3.app
- name: Xcode version
  run: /usr/bin/xcodebuild -version
- name: iPhone 11 Test
run: xcodebuild test -scheme weather-ios/WeatherMether/WeatherMetherTests -workspace weather-ios/WeatherMether/WeatherMether.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3'
