name: build  


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
    
jobs:
  build:
  runs-on: macOS-latest

steps:
- name: Checkout
- uses: actions/checkout@v2
- name: Force xcode 11
run: sudo xcode-select -switch /Applications/Xcode_11.4.app
- name: iPhone 11 Test
run: xcodebuild test -scheme WeatherMetherTests -workspace WeatherMether.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.4'
